---

- hosts: localhost
  tasks:
    - name: Get your current IP address
      uri:
        url: http://checkip.amazonaws.com/
        return_content: yes
      register: my_ip

    - name: Create simple security group
      ec2_group:
        name: webservers
        description: A security group for your current IP
        region: us-west-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Add EC2 instances
      ec2:
        key_name: nickhammond
        instance_type: t2.nano
        image: ami-f2b39792
        region: us-west-1
        group: webservers
        wait: yes
        instance_tags:
          application: nickhammond
        exact_count: 2
        count_tag:
          application: nickhammond
      register: ec2_instances

    - name: Create the ELB only listening over port 80
      ec2_elb_lb:
        name: nickhammond-load-balancer
        state: present
        region: us-west-1
        zones:
          - us-west-1a
          - us-west-1b
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80

    - name: Add each EC2 instance to the ELB
      ec2_elb:
        state: present
        ec2_elbs: nickhammond-load-balancer
        region: "{{ item.region }}"
        instance_id: "{{ item.id }}"
      with_items: "{{ ec2_instances.tagged_instances }}"

    - name: Store EC2 instance IPs to provision against
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2_instance_ips
      with_items: "{{ ec2_instances.tagged_instances }}"

    - name: Add EC2 instances as known hosts
      known_hosts:
        name: "{{ item.public_ip }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_ip) }}"
      with_items: "{{ ec2_instances.tagged_instances }}"

- hosts: ec2_instance_ips
  remote_user: ubuntu
  tasks:
    - name: Install nginx
      become: True
      apt:
        name: nginx
        state: present

    # Update default page at /usr/share/nginx/html/index.html
    # Restart nginx
